site_name: encode-utils-cli
repo_url: https://github.com/deadnews/encode-utils-cli
edit_uri: blob/main/docs/

nav:
  - CLI Reference: index.md

watch:
  - src

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        name: Switch to light mode
        icon: material/brightness-auto
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        name: Switch to dark mode
        icon: material/brightness-7
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        name: Switch to system preference
        icon: material/brightness-4
  features:
    - content.code.copy
    - search.highlight

markdown_extensions:
  - attr_list
  - mkdocs-click
  - pymdownx.superfences
  - toc:
      permalink: true
