site_name: encode-utils-cli
repo_url: https://github.com/deadnews/encode-utils-cli
edit_uri: blob/main/docs/
theme:
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - attr_list
  - mkdocs-click
  - pymdownx.superfences
