site_name: encode-utils-cli
repo_url: https://github.com/deadnews/encode-utils-cli
edit_uri: blob/main/docs/

nav:
  - Overview: index.md
  - CLI Reference: cli.md

watch:
  - src
  - README.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        name: Switch to light mode
        icon: material/brightness-auto
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        name: Switch to dark mode
        icon: material/brightness-7
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        name: Switch to system preference
        icon: material/brightness-4
  features:
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.follow

markdown_extensions:
  - attr_list
  - mkdocs-click
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
