name: Deploy docs

on:
  push:
    branches: [main]
    paths:
      - "src/**/*.py"

permissions:
  contents: write

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup vapoursynth
        uses: deadnews/setup-vapoursynth@v0.0.2

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          cache: poetry

      - name: Install deps
        run: poetry install

      - name: Deploy docs
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          poetry run mkdocs gh-deploy --force
